name: Deploy to npm and Auto Version Bump

on:
  push:
    branches:
      - main
      - beta
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "^18.17 || >=20.6.1"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci --include=dev

      - name: Run tests
        continue-on-error: true
        run: |
              npm run test 
              
      - name: Build Package
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.ALLEN_COMMON_NPM_TOKEN }}" > ~/.npmrc

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ALLEN_COMMON_NPM_TOKEN }}
        run: |
          git config --global user.name "Pr3rna-allen"
          git config --global user.email "prerana.singh@allen.in"
          npx semantic-release